import assert from "node:assert/strict";

import { getSupportedReportLevels, renderLevelReport } from "../src/report.mjs";

const sample = {
  generated_at: "2026-03-31T00:00:00.000Z",
  status: "full",
  life_code_index: 72.4,
  adjusted_life_code_index: 55.8,
  data_coverage: 1,
  risk_score: 0.31,
  risk_score_raw: 0.44,
  wealth_score: 0.52,
  wealth_score_raw: 0.67,
  mission_signal: 0.48,
  mission_signal_raw: 0.62,
  identity_layer: "Identity sample",
  analysis_layer: "Analysis sample",
  timeline_layer: "Timeline sample",
  action_layer: "Action sample",
  opportunity_windows: [12, 18, 27],
  transformation_windows: [33, 48],
};

const levels = getSupportedReportLevels();
assert.deepEqual(levels, [1, 2, 3, 4, 5, 6, 7, 8, 9]);

for (const level of levels) {
  const report = renderLevelReport(level, sample);
  assert.match(report, /^# Level /);
  assert.match(report, /Report generated by Life Code OS Engine v1|Full Life Code Book generated by Life Code OS Engine v1/);
  assert.ok(report.includes("Identity sample") || report.includes("Analysis sample") || report.includes("Timeline sample"));
}

assert.throws(() => renderLevelReport(10, sample), /Unsupported report level/);

console.log("report smoke tests passed");
