name = "life-code-api"
main = "src/index.js"
compatibility_date = "2024-11-12"
account_id = "f3f9e76222dcb488d5e303e29e8ba192"

# Sau khi deploy: gắn route tùy chọn, ví dụ:
# routes = [{ pattern = "api.lifecode.iai.one/*", zone_name = "iai.one" }]
