const LEVEL_TEMPLATES = {
  1: `# Level 1 — Self Signal Report

**Generated:** {{generated_at}}
**Status:** {{status}}

---

## Core Summary

| Metric | Value |
|--------|-------|
| Life Code Index | {{life_code_index}} |
| Adjusted LCI | {{adjusted_life_code_index}} |
| Data Coverage | {{data_coverage}} |
| Risk Score | {{risk_score}} |
| Wealth Score | {{wealth_score}} |
| Mission Signal | {{mission_signal}} |

---

## 1. Identity Layer

{{identity_layer}}

---

## 2. Analysis Layer

{{analysis_layer}}

---

## 3. Timeline Layer

{{timeline_layer}}

---

## 4. Action Layer

{{action_layer}}

---

## 5. Key Insights

### Risk Assessment
- Raw Risk Score: {{risk_score_raw}}
- Adjusted Risk Score: {{risk_score}}

### Wealth Assessment
- Raw Wealth Score: {{wealth_score_raw}}
- Adjusted Wealth Score: {{wealth_score}}

### Mission Assessment
- Raw Mission Signal: {{mission_signal_raw}}
- Adjusted Mission Signal: {{mission_signal}}

---

## 6. Timeline Windows

### Opportunity Windows
{{opportunity_windows}}

### Transformation Windows
{{transformation_windows}}

---

*Report generated by Life Code OS Engine v1*`,
  2: `# Level 2 — Inner Architecture Report

**Generated:** {{generated_at}}
**Status:** {{status}}

---

## Core Summary

| Metric | Value |
|--------|-------|
| Life Code Index | {{life_code_index}} |
| Adjusted LCI | {{adjusted_life_code_index}} |
| Data Coverage | {{data_coverage}} |

---

## 1. Internal Structure Map

{{analysis_layer}}

---

## 2. Risk Base Map

- Risk Score: {{risk_score}}
- Raw Risk Score: {{risk_score_raw}}

---

## 3. 3-Year Direction

{{timeline_layer}}

---

## 4. Confidence Assessment

- Data Coverage: {{data_coverage}}
- Status: {{status}}

---

*Report generated by Life Code OS Engine v1*`,
  3: `# Level 3 — Behavior Code Report

**Generated:** {{generated_at}}
**Status:** {{status}}

---

## 1. Behavior Pattern Analysis

{{analysis_layer}}

---

## 2. Stress Profile

- Risk Score: {{risk_score}}
- Raw Risk Score: {{risk_score_raw}}

---

## 3. Work Rhythm

{{action_layer}}

---

## 4. Energy Leakage Zones

{{identity_layer}}

---

*Report generated by Life Code OS Engine v1*`,
  4: `# Level 4 — Work & Wealth Code Report

**Generated:** {{generated_at}}
**Status:** {{status}}

---

## 1. Wealth Pattern

- Wealth Score: {{wealth_score}}
- Raw Wealth Score: {{wealth_score_raw}}

---

## 2. Financial Leakage Map

{{analysis_layer}}

---

## 3. Work Archetype

{{identity_layer}}

---

## 4. Growth & Defense Periods

{{timeline_layer}}

---

## 5. Financial Actions

{{action_layer}}

---

*Report generated by Life Code OS Engine v1*`,
  5: `# Level 5 — Relationship Field Report

**Generated:** {{generated_at}}
**Status:** {{status}}

---

## 1. Relationship Field Map

{{identity_layer}}

---

## 2. Trust Map

{{analysis_layer}}

---

## 3. Conflict Triggers

- Risk Score: {{risk_score}}
- Raw Risk Score: {{risk_score_raw}}

---

## 4. Relationship Support

- Mission Signal: {{mission_signal}}
- Wealth Score: {{wealth_score}}

---

## 5. Relationship Actions

{{action_layer}}

---

*Report generated by Life Code OS Engine v1*`,
  6: `# Level 6 — Life Timeline Report

**Generated:** {{generated_at}}
**Status:** {{status}}

---

## 1. Timeline 0–99

{{timeline_layer}}

---

## 2. Current Stage

{{analysis_layer}}

---

## 3. Risk Windows

- Risk Score: {{risk_score}}
- Raw Risk Score: {{risk_score_raw}}

---

## 4. Peak Windows

{{opportunity_windows}}

---

## 5. Transformation Windows

{{transformation_windows}}

---

## 6. Timeline Actions

{{action_layer}}

---

*Report generated by Life Code OS Engine v1*`,
  7: `# Level 7 — Body Intelligence Report

**Generated:** {{generated_at}}
**Status:** {{status}}

---

## 1. Health Intelligence Map

{{analysis_layer}}

---

## 2. Face Map

{{identity_layer}}

---

## 3. Hand Map

{{timeline_layer}}

---

## 4. Foot Grounding Map

{{action_layer}}

---

## 5. Health Recommendations

- Risk Score: {{risk_score}}
- Raw Risk Score: {{risk_score_raw}}

---

*Report generated by Life Code OS Engine v1*`,
  8: `# Level 8 — Mission Path Report

**Generated:** {{generated_at}}
**Status:** {{status}}

---

## 1. Mission Alignment

{{identity_layer}}

---

## 2. Repeated Lessons

{{analysis_layer}}

---

## 3. Service Path

{{action_layer}}

---

## 4. Mission Activation

- Mission Signal: {{mission_signal}}
- Raw Mission Signal: {{mission_signal_raw}}

---

## 5. Legacy Fit

{{timeline_layer}}

---

*Report generated by Life Code OS Engine v1*`,
  9: `# Level 9 — Full Life Code Book

**Generated:** {{generated_at}}
**Status:** {{status}}

---

## Complete Life Profile

| Metric | Value |
|--------|-------|
| Life Code Index | {{life_code_index}} |
| Adjusted LCI | {{adjusted_life_code_index}} |
| Data Coverage | {{data_coverage}} |
| Risk Score | {{risk_score}} |
| Wealth Score | {{wealth_score}} |
| Mission Signal | {{mission_signal}} |

---

## Part I: Identity & Core Structure

{{identity_layer}}

---

## Part II: Analysis & Patterns

{{analysis_layer}}

---

## Part III: Timeline & Windows

{{timeline_layer}}

### Opportunity Windows
{{opportunity_windows}}

### Transformation Windows
{{transformation_windows}}

---

## Part IV: Risk & Wealth

- Risk Score: {{risk_score}} (Raw: {{risk_score_raw}})
- Wealth Score: {{wealth_score}} (Raw: {{wealth_score_raw}})

---

## Part V: Mission & Legacy

- Mission Signal: {{mission_signal}} (Raw: {{mission_signal_raw}})

---

## Part VI: Action Plan

{{action_layer}}

---

*Full Life Code Book generated by Life Code OS Engine v1*`,
};

function stringifyValue(value) {
  if (Array.isArray(value)) return value.join(", ") || "N/A";
  if (value === undefined || value === null || value === "") return "N/A";
  return String(value);
}

export function getSupportedReportLevels() {
  return Object.keys(LEVEL_TEMPLATES).map(Number);
}

export function renderLevelReport(level, data) {
  const template = LEVEL_TEMPLATES[level];
  if (!template) {
    throw new Error(`Unsupported report level: ${level}`);
  }

  return template.replace(/\{\{\s*([\w_]+)\s*\}\}/g, (_, key) => stringifyValue(data[key]));
}
